[package]
authors = ["Ryan Kurte <ryankurte@gmail.com>"]
description = "Driver for the Semtec sx1280 2.4GHz RF IC"
edition = "2018"
license = "MPL-2.0"
name = "radio-sx128x"
repository = "https://github.com/rust-iot/rust-radio-sx128x"
version = "0.15.0"

[metadata]
[metadata.binstall]
bin-dir = "{ bin }-{ target }{ format }"
pkg-fmt = "tar"
pkg-url = "{ repo }/releases/download/v{ version }/sx128x-util-{ target }.tgz"

[[bin]]
name = "sx128x-util"
path = "src/util/main.rs"
required-features = ["util"]

[dependencies]
bitflags = "1.0.4"
embedded-hal = "1.0.0-alpha.4"
libc = "0.2.70"
log = "0.4.6"
radio = "0.8.1"

[dependencies.serde]
version = "1.0.118"
optional = true
features = [ "derive" ]

[dependencies.crc16]
optional = true
version = "0.4.0"

[dependencies.driver-cp2130]
optional = true
version = "1.0.0-alpha.2"

[dependencies.driver-pal]
default-features = false
version = "0.8.0-alpha.1"

[dependencies.failure]
default-features = false
features = ["derive"]
version = "0.1.7"

[dependencies.hex]
optional = true
version = "0.4.2"

[dependencies.humantime]
optional = true
version = "2.0.1"

[dependencies.linux-embedded-hal]
optional = true
version = "0.4.0-alpha.0"

[dependencies.pcap-file]
optional = true
version = "1.1.1"

[dependencies.structopt]
optional = true
version = "0.3.21"

[dependencies.tracing]
optional = true
version = "0.1.14"

[dependencies.tracing-subscriber]
optional = true
version = "0.2.5"

[dev-dependencies]
color-backtrace = "0.5.0"
env_logger = "0.8.2"
serde_derive = "1.0.118"
toml = "0.5.8"

[dev-dependencies.driver-pal]
default-features = false
features = ["mock", "hal"]
version = "0.8.0-alpha.0"

[dev-dependencies.serde]
features = ["derive"]
version = "1.0.118"

[features]
default = ["util", "serde", "driver-pal/hal-cp2130", "driver-pal/hal-linux"]
poll-irq = []
tests = ["driver-pal/mock"]
util = ["structopt", "tracing", "tracing-subscriber", "humantime", "pcap-file", "crc16", "driver-pal/hal", "failure/std", "hex"]
atures = ["util"]
