[package]
authors = ["Ryan Kurte <ryankurte@gmail.com>"]
description = "Driver for the Semtec sx1280 2.4GHz RF IC"
repository = "https://github.com/ryankurte/rust-radio-sx128x"
license = "MPL-2.0"
name = "radio-sx128x"
version = "0.14.1-alpha.3"
edition = "2018"

[features]
default = ["util", "serde"]
poll-irq = []
tests = [ "driver-pal/mock" ]
util = ["structopt", "tracing", "tracing-subscriber", "humantime", "pcap-file", "crc16", "driver-pal/hal", "driver-pal/hal-cp2130", "failure/std"]

[dependencies]
bitflags = "1.0.4"
libc = "0.2.70"
log = "0.4.6"
radio = "0.7.0"

pcap-file = { version = "1.1.1", optional = true }

linux-embedded-hal = { version = "0.3.0", optional = true }
driver-cp2130 = { version = "1.0.0-alpha", optional = true }
crc16 = { version = "0.4.0", optional = true }

[dependencies.failure]
version = "0.1.7"
features = [ "derive" ]
default-features = false

[dependencies.embedded-hal]
version = "=1.0.0-alpha.2"

[dependencies.driver-pal]
version = "0.7.0"
default-features = false
git = "https://github.com/ryankurte/rust-embedded-spi.git"
branch = "master"

#[target.'cfg(unix)'.dependencies.driver-pal]
#version = "00.6.1
#features = [ "hal-linux" ]

[dependencies.humantime]
optional = true
version = "1.2.0"

[dependencies.serde]
features = ["derive"]
optional = true
version = "1.0"

[dependencies.tracing]
optional = true
version = "0.1.14"

[dependencies.tracing-subscriber]
optional = true
version = "0.2.5"

[dependencies.structopt]
optional = true
version = "0.3.11"

[dev-dependencies]
color-backtrace = "0.1.3"

[[bin]]
name = "sx128x-util"
path = "src/util/main.rs"
required-features = ["util"]

[patch.crates-io]
radio = { git = "https://github.com/ryankurte/rust-radio.git", branch = "master" }

# Patch for transactional SPI, remove on e-h@v1.0.0-alpha.3
embedded-hal = { git = "https://github.com/rust-embedded/embedded-hal.git", branch = "master" }
# Patches for transactional SPI, blocked on e-h@v1.0.0-alpha.3, remove when upstreamed
#driver-pal = { git = "https://github.com/ryankurte/rust-embedded-spi.git", branch = "master" }
driver-cp2130 = { git = "https://github.com/ryankurte/rust-driver-cp2130.git", branch = "master" }
linux-embedded-hal = { git = "https://github.com/ryankurte/linux-embedded-hal.git", branch = "feature/spi-transactions" }

# Fix for libusb-sys package discovery
libusb-sys = { git = "https://github.com/cmsd2/libusb-sys" } 

#driver-cp2130 = { path = "../rust-driver-cp2130" }
#embedded-hal = { path = "../embedded-hal" }
#driver-pal = { path = "../rust-driver-pal" }
#linux-embedded-hal = { path = "../linux-embedded-hal" }

